<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <Content Remove="wwwroot\assets\img\05074e9f-62b1-48fe-b84a-a4c6f86f6c53.jpg" />
    <Content Remove="wwwroot\assets\img\b94c232b-46fc-4e55-b32b-b6b3a345443a.jpg" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="8.0.0">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Livros.Application\Livros.Application.csproj" />
    <ProjectReference Include="..\Livros.Domain\Livros.Domain.csproj" />
    <ProjectReference Include="..\Livros.Infrastructure\Livros.Infrastructure.csproj" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="wwwroot\assets\fonts\inter\" />
    <Folder Include="wwwroot\assets\icons\boxicons\fonts\" />
  </ItemGroup>

</Project>
