<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net8.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
  </PropertyGroup>

  <ItemGroup>
    <ProjectReference Include="..\Livros.Application\Livros.Application.csproj" />
    <ProjectReference Include="..\Livros.Infrastructure\Livros.Infrastructure.csproj" />
  </ItemGroup>

</Project>
